In [1]:
!pip3 install torch torchvision

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
from IPython import display
import numpy as np
import random
import torch

Создайте случайный FloatTensor размера 3x4x5

In [3]:
a = torch.FloatTensor(3, 4, 5)
a

tensor([[[3.2241e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45],
         [5.6052e-45, 1.4013e-45, 2.9427e-44, 1.5316e-42, 0.0000e+00],
         [1.4013e-45, 0.0000e+00, 1.4013e-45, 4.2039e-44, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[3.2239e-35, 0.0000e+00, 3.2241e-35, 0.0000e+00, 1.5344e-42],
         [0.0000e+00, 3.2241e-35, 0.0000e+00, 9.8091e-45, 0.0000e+00],
         [3.2241e-35, 0.0000e+00, 1.5358e-42, 0.0000e+00, 3.2241e-35],
         [0.0000e+00, 9.8091e-45, 0.0000e+00, 3.2241e-35, 0.0000e+00]],

        [[1.5372e-42, 0.0000e+00, 3.2241e-35, 0.0000e+00, 9.8091e-45],
         [0.0000e+00, 3.2241e-35, 0.0000e+00, 1.5386e-42, 0.0000e+00],
         [3.2241e-35, 0.0000e+00, 9.8091e-45, 0.0000e+00, 3.2241e-35],
         [0.0000e+00, 1.5442e-42, 0.0000e+00, 3.2241e-35, 0.0000e+00]]])

Выведите его форму (shape)

In [4]:
a.shape

torch.Size([3, 4, 5])

Приведите его к форме 6х10

In [5]:
c = a.reshape(6, 10)
c

tensor([[3.2241e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45, 5.6052e-45,
         1.4013e-45, 2.9427e-44, 1.5316e-42, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.4013e-45, 4.2039e-44, 0.0000e+00, 0.0000e+00,
         0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00],
        [3.2239e-35, 0.0000e+00, 3.2241e-35, 0.0000e+00, 1.5344e-42, 0.0000e+00,
         3.2241e-35, 0.0000e+00, 9.8091e-45, 0.0000e+00],
        [3.2241e-35, 0.0000e+00, 1.5358e-42, 0.0000e+00, 3.2241e-35, 0.0000e+00,
         9.8091e-45, 0.0000e+00, 3.2241e-35, 0.0000e+00],
        [1.5372e-42, 0.0000e+00, 3.2241e-35, 0.0000e+00, 9.8091e-45, 0.0000e+00,
         3.2241e-35, 0.0000e+00, 1.5386e-42, 0.0000e+00],
        [3.2241e-35, 0.0000e+00, 9.8091e-45, 0.0000e+00, 3.2241e-35, 0.0000e+00,
         1.5442e-42, 0.0000e+00, 3.2241e-35, 0.0000e+00]])

Создайте случайный IntTensor размера 10

In [6]:
b =  torch.IntTensor(10)
b

tensor([-1055015824,       32666,   103520912,           0,       65536,
              65537,       65537,       65537,       65537,       65537],
       dtype=torch.int32)

Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [7]:
d = b.mul(c)
d

tensor([[-3.4014e-26,  0.0000e+00,  0.0000e+00,  0.0000e+00,  9.1835e-41,
          3.6735e-40,  9.1837e-41,  1.9286e-39,  1.0038e-37,  0.0000e+00],
        [-1.4784e-36,  0.0000e+00,  1.4506e-37,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  9.1837e-41,  0.0000e+00],
        [-3.4013e-26,  0.0000e+00,  3.3376e-27,  0.0000e+00,  1.0056e-37,
          0.0000e+00,  2.1130e-30,  0.0000e+00,  6.4286e-40,  0.0000e+00],
        [-3.4015e-26,  0.0000e+00,  1.5899e-34,  0.0000e+00,  2.1130e-30,
          0.0000e+00,  6.4286e-40,  0.0000e+00,  2.1130e-30,  0.0000e+00],
        [-1.6218e-33,  0.0000e+00,  3.3377e-27,  0.0000e+00,  6.4285e-40,
          0.0000e+00,  2.1130e-30,  0.0000e+00,  1.0084e-37,  0.0000e+00],
        [-3.4015e-26,  0.0000e+00,  1.0154e-36,  0.0000e+00,  2.1130e-30,
          0.0000e+00,  1.0120e-37,  0.0000e+00,  2.1130e-30,  0.0000e+00]])

Умножьте тензор матрично на себя, чтобы результат был размерности 6x6 Подсказка: .dot может не подойти

In [12]:
z = c.t()
e = torch.matmul(c, z)
e

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [13]:
z

tensor([[3.2241e-35, 1.4013e-45, 3.2239e-35, 3.2241e-35, 1.5372e-42, 3.2241e-35],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.4013e-45, 3.2241e-35, 1.5358e-42, 3.2241e-35, 9.8091e-45],
        [0.0000e+00, 4.2039e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 1.5344e-42, 3.2241e-35, 9.8091e-45, 3.2241e-35],
        [5.6052e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 3.2241e-35, 9.8091e-45, 3.2241e-35, 1.5442e-42],
        [2.9427e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [1.5316e-42, 1.4013e-45, 9.8091e-45, 3.2241e-35, 1.5386e-42, 3.2241e-35],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [26]:
x=torch.tensor([1.0],requires_grad=True)
z=torch.tensor([0.5],requires_grad=True)
t=torch.tensor([2.0],requires_grad=True)
 
y= torch.pow(x,3) + z - 75*t 
 
torch.autograd.backward([y]) 
 
print(x.grad)   
print(z.grad)
print(t.grad)

tensor([3.])
tensor([1.])
tensor([-75.])


Создайте единичный тензор размера 5x6

In [16]:
q  = torch.eye(5, 6)
q

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

Переведите его в формат numpy

In [17]:
w = q.numpy() 
w

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)